name        : libxscrnsaver
version     : 1.2.2
release     : 5
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libXScrnSaver-1.2.2.tar.bz2 : 8ff1efa7341c7f34bcf9b17c89648d6325ddaae22e3904e091794e0b4426ce1d
license     : GPL-3.0+
summary     : X11 Screen Saver extension client library
builddeps   :
    - pkgconfig32(xext)
    - pkgconfig(scrnsaverproto)
    - pkgconfig32(x11)
    - libgcc-32bit
    - glibc-32bit-devel
description : |
    The Screen Saver extension allows clients behaving as screen savers to register themselves with the X server, to better integrate themselves with the running session.
patterns   :
    - /usr/share
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
