name       : libxscrnsaver
version    : 1.2.2
release    : 7
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXScrnSaver-1.2.2.tar.bz2 : 8ff1efa7341c7f34bcf9b17c89648d6325ddaae22e3904e091794e0b4426ce1d
license    : MIT
summary    : X11 Screen Saver extension client library
component  : xorg.library
description: |
    The Screen Saver extension allows clients behaving as screen savers to
    register themselves with the X server, to better integrate themselves
    with the running session.
builddeps  :
    - pkgconfig(scrnsaverproto)
    - pkgconfig32(xext)
    - pkgconfig32(x11)
patterns   :
    - devel :
        - /usr/share/man
emul32     : yes
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
